name: e2e Tests

on:
  push:
    paths:
      - 'e2e/**'
      - 'api/**'
      - 'client/**'
      - '.github/workflows/e2e-tests.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'

  workflow_dispatch:


jobs:
  e2e-tests:
    name: e2e tests
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: eccc
          POSTGRES_PASSWORD: eccc
          POSTGRES_DB: eccc_db_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      TESTING: 'true'
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: eccc
      DB_PASSWORD: eccc
      DB_NAME: eccc_db_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GDAL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev

      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: 'api/uv.lock'

      - name: Install Python 3.12
        run: uv python install 3.12

      - name: Install dependencies
        working-directory: api
        run: uv sync --frozen

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        working-directory: .
        run: pnpm install

      - name: Install Chromium browser
        working-directory: e2e
        run: npx playwright install --with-deps chromium

      - name: Run e2e tests
        working-directory: e2e
        run: pnpm test:ci

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30